// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxkodxqowdwvkbcdflmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4a29keHFvd2R3dmtiY2RmbG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMDgwNjMsImV4cCI6MjA1MDY4NDA2M30.TmVm_3YxpZpPgIvsMzID7GBXvrvwH3PfbV2bPqEaqEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);